name: Deploy to Yegara via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build your website
        run: npm run build # Or your build command

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5 # Replace with the correct action and version
        with:
          server: ${{ secrets.ftp.yegara.com }} # Note: changed from 'host'
          username: ${{ secrets.myftpuser }}
          password: ${{ secrets.shakiso12345 }}
          port: 21 # Add this if the FTP action requires a port. Often it is 21
          local-dir: ./build # Make sure this path is correct.
          server-dir: ${{ secrets.public_html }} # Note: changed from 'remote_dir'