   name: 🚀 Deploy to Yegara
   on:
     push:
       branches:
         - main  # or your deployment branch
   jobs:
     ftp-deploy:
       name: 📦 Upload via FTP
       runs-on: ubuntu-latest
       steps:
       - name: 🔄 Checkout code
         uses: actions/checkout@v3
       - name: 📤 FTP Deploy
         uses: SamKirkland/FTP-Deploy-Action@v4.3.4
         with:
           server: ${{ secrets.FTP_HOST }}
           username: ${{ secrets.myftpuser }}
           password: ${{ secrets.321shakiso123 }}
           server-dir: ${{ secrets.public_html }}