name: Deploy Website to Yegara FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3
      - name: Deploy Website via FTP to Yegara
        uses: SamKirkland/ftp-deploy-action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.myftpuser }}
          password: ${{ secrets.shakiso12345 }}
          local-dir: './build/'             # Change if your website files are in a subfolder
          server-dir: ${{ secrets.public_html }}  # Change to your Yegara site root if different