name: Deploy to Yegara via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build your website
        run: npm run build # Or your build command

      # --- IMPORTANT: Replace 'ftp-deploy-action/ftp-deploy@vX.Y.Z' with the correct action ---
      # --- and adjust 'server', 'username', etc. based on the action's specific documentation ---
      - name: Deploy to FTP
        uses: sebastianpopp/ftp-action@v4 # Example: using a specific, known-good action
        with:
          # Mapping your GitHub secrets to the action's expected inputs
          server: ${{ secrets.ftp.yegara.com }}            # Maps your FTP_HOST secret to the action's 'server' input
          username: ${{ secrets.myftpuser }}
          password: ${{ secrets.shakiso12345 }}
          port: 21                                  # Standard FTP port, add if needed by the action
          local-dir: ./build                        # Your local build output directory
          server-dir: ${{ secrets.public_html }} # The directory on the FTP server
          # You might need to add other inputs based on the action's docs, like 'protocol' (ftp/sftp)
          # protocol: ftp # Example if needed