on: push
name: Deploy Website on Push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.yourdomain.com
        username: ${{ secrets.myftpuser }}
        password: ${{ secrets.shakiso12345 }}
        protocol: ftps
        server-dir: public_html/